# extras/foot/oasis_night_dark.ini
# name: Oasis Night Dark
# author: uhs-robert

[colors-dark]
cursor=040E25 F0E68C
foreground=E8F1FF
background=040E25

selection-foreground=E8F1FF
selection-background=24364D

search-box-no-match=E8F1FF 666666
search-box-match=040E25 CDC673

urls=87CEEB
jump-labels=040E25 CDC673

regular0=040E25
regular1=FF7979
regular2=7FCF78
regular3=F0E68C
regular4=81C0FF
regular5=C695FF
regular6=68C0B6
regular7=FFF7D7

bright0=536B83
bright1=FFA0A0
bright2=A3E39A
bright3=F8B471
bright4=87CEEB
bright5=D2ADFF
bright6=8FD1C7
bright7=F7F4E9
16=FF9633
17=FF7979

# extras/foot/oasis_night_light_3.ini
# name: Oasis Night Light 3
# author: uhs-robert

[colors-light]
cursor=e6dbb2 784313
foreground=52412d
background=e6dbb2

selection-foreground=52412d
selection-background=dbca8f

search-box-no-match=4e260e e1b69d
search-box-match=350808 dd6f6f

urls=244958
jump-labels=350808 dd6f6f

regular0=5d3c33
regular1=a11010
regular2=33592f
regular3=57511d
regular4=125190
regular5=6b20c3
regular6=2d5753
regular7=504311

bright0=593e30
bright1=a11010
bright2=305a29
bright3=774412
bright4=1f566c
bright5=6a20c4
bright6=2c5851
bright7=4b4429
16=623b18
17=a11216
