[main]
initial-color-theme=dark
# initial-window-size-pixels=700x500
include = ~/.config/foot/themes/oasis_starlight.ini
font=FantasqueSansM Nerd Font:pixelsize=14:antialias=true

pad=4x4 center

[csd]
preferred = none

[key-bindings]
show-urls-copy = Control+Shift+p
